// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CookieButtonsController from "./cookie_buttons_controller"
application.register("cookie-buttons", CookieButtonsController)

import CookiesController from "./cookies_controller"
application.register("cookies", CookiesController)

import FormResetController from "./form_reset_controller"
application.register("form-reset", FormResetController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)
